receivers:
  oracledb:
    # driver name: oracle
    # username: otel
    # password: password
    # host: localhost
    # container exposed port: 51521
    # Oracle DB service name: XE
    # Refer to Oracle Go Driver go_ora documentation for full connection string options
    datasource: "oracle://otel:password@localhost:51521/XE"
  otlp:
    protocols:
      http:
  smartagent/processlist:
    type: processlist
  smartagent/signalfx-forwarder:
    type: signalfx-forwarder

processors:
  batch:
  timestamp:

extensions:
  smartagent:

exporters:
  logging:

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - logging
    metrics:
      receivers:
      - smartagent/signalfx-forwarder
      - oracledb
      processors:
      - timestamp
      exporters:
      - logging
    logs:
      receivers:
      - smartagent/processlist
      processors:
      - batch
      exporters:
      - logging
